name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 4.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  community_material_icon: ^5.9.55
  file_picker: ^5.1.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.5.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
